# NumPy Fundamentals

This notebook walks through core NumPy concepts with short, focused examples and a couple of practice problems.


In [1]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)


## What Is NumPy
NumPy is the foundational numerical computing library in Python. It provides:
- A fast, memory‑efficient N‑dimensional array (`ndarray`).
- Vectorized math operations (no explicit Python loops).
- A large collection of functions for linear algebra, statistics, random sampling, and more.


## NumPy vs Python Lists (Speed + Functionality)
Python lists are flexible, but numeric computation on lists uses Python loops and is much slower.
NumPy arrays store data in contiguous memory and run fast, vectorized operations in C.


In [2]:
import timeit

py_list = list(range(1_000_000))
np_array = np.arange(1_000_000)

def list_add():
    return [x + 1 for x in py_list]

def numpy_add():
    return np_array + 1

list_time = timeit.timeit(list_add, number=5)
numpy_time = timeit.timeit(numpy_add, number=5)

list_time, numpy_time


(0.08912308292929083, 0.001214458025060594)

## Applications of NumPy
- Data science and machine learning preprocessing
- Signal and image processing
- Scientific simulations and numerical methods
- Linear algebra and statistics
- Interfacing with C/C++ and GPU libraries


## The Basics
Creating arrays, checking shape, size, and dtype.


In [3]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])

(a, a.shape, a.size, a.dtype), (b, b.shape, b.size, b.dtype)


((array([1, 2, 3]), (3,), 3, dtype('int64')),
 (array([[1, 2, 3],
         [4, 5, 6]]), (2, 3), 6, dtype('int64')))

## Accessing / Changing Specific Elements (Slicing)


In [4]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

arr[0, 0]        # first element
arr[:, 1]        # second column
arr[1, :]        # second row
arr[0, 1:3]      # slice from row 0

arr[2, 2] = 99
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 99, 12]])

## Initializing Different Arrays


In [5]:
np.zeros((2, 3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2, 3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((2, 3), 7)


array([[7, 7, 7],
       [7, 7, 7]])

In [8]:
np.random.random((2, 3))


array([[0.791, 0.333, 0.154],
       [0.41 , 0.872, 0.22 ]])

In [9]:
np.eye(4)  # identity matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [11]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Problem #1
**How do you initialize this array?**

Goal: a 5×5 array of 1s with a 3×3 block of 0s in the center.


In [12]:
# Solution
prob1 = np.ones((5, 5), dtype=int)
prob1[1:4, 1:4] = 0
prob1


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

## Be Careful When Copying Variables
Assigning one array to another does **not** copy the data.
Use `.copy()` for an independent copy.


In [13]:
a = np.array([1, 2, 3])
b = a           # view/reference
c = a.copy()    # deep copy

a[0] = 99

a, b, c


(array([99,  2,  3]), array([99,  2,  3]), array([1, 2, 3]))

## Basic Mathematics


In [14]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x + y, x - y, x * y, x / y


(array([5, 7, 9]),
 array([-3, -3, -3]),
 array([ 4, 10, 18]),
 array([0.25, 0.4 , 0.5 ]))

In [15]:
angles = np.array([0, np.pi/2, np.pi])
np.sin(angles), np.cos(angles)


(array([0., 1., 0.]), array([ 1.,  0., -1.]))

## Linear Algebra


In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

A @ B


array([[ 4,  4],
       [10,  8]])

In [17]:
np.linalg.det(A), np.linalg.inv(A)


(np.float64(-2.0000000000000004),
 array([[-2. ,  1. ],
        [ 1.5, -0.5]]))

In [18]:
b = np.array([1, 0])
np.linalg.solve(A, b)


array([-2. ,  1.5])

## Statistics


In [19]:
data = np.array([[1, 2, 3], [4, 5, 6]])

np.min(data), np.max(data), np.mean(data), np.std(data)


(np.int64(1), np.int64(6), np.float64(3.5), np.float64(1.707825127659933))

In [20]:
np.sum(data, axis=0), np.sum(data, axis=1)


(array([5, 7, 9]), array([ 6, 15]))

## Reorganizing Arrays


In [21]:
arr = np.arange(1, 13)
print(arr)
arr.reshape((3, 4))


[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

np.vstack([v1, v2])


array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.hstack([v1, v2])


array([1, 2, 3, 4, 5, 6])

## Load Data From a File
We'll write a small CSV, then load it with `genfromtxt`.


In [24]:
from pathlib import Path

csv_path = Path("np_data.csv")
np.savetxt(csv_path, np.array([[1, 2, 3], [4, 5, 6]]), delimiter=",", fmt="%d")

loaded = np.genfromtxt(csv_path, delimiter=",")
loaded


array([[1., 2., 3.],
       [4., 5., 6.]])

## Advanced Indexing and Boolean Masking


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr[[0, 2, 5]]  # fancy indexing


array([1, 3, 6])

In [26]:
mask = arr > 3
mask, arr[mask]


(array([False, False, False,  True,  True,  True]), array([4, 5, 6]))

In [27]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix[matrix % 2 == 0]


array([2, 4, 6, 8])

## Problem #2
**How do you index these values?**

Given:
```
[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20]]
```

Extract:
- `9`
- `[8, 9, 10]`
- `[[6, 7], [11, 12]]`
- `[2, 7, 12, 17]`


In [28]:
# Solution
m = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

m[1, 3]          # 9
m[1, 2:5]        # [8, 9, 10]
m[1:3, 0:2]      # [[6, 7], [11, 12]]
m[:, 1]          # [2, 7, 12, 17]


array([ 2,  7, 12, 17])