# PyTorch Fundamentals (Rebuilt)

Clean walkthrough with comments, headers, and subheaders for your listed topics.

In [2]:
# Import core libraries for deep learning and numerical computing
import torch  # PyTorch: framework for neural networks and tensor computations
import numpy as np  # NumPy: fundamental package for numerical computing

print('torch:', torch.__version__)
print('numpy:', np.__version__)

torch: 2.10.0
numpy: 2.3.2


## 13. Introduction to tensors

In [3]:
# Tensors are the fundamental data structure in PyTorch
# They are n-dimensional arrays that can be processed on GPUs for fast computation
# ndim = number of dimensions, shape = size of each dimension

scalar = torch.tensor(7)  # 0D tensor: just a single number
vector = torch.tensor([1, 2, 3])  # 1D tensor: ordered list of numbers
matrix = torch.tensor([[1, 2], [3, 4]])  # 2D tensor: grid of numbers (rows × cols)
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3D tensor: cube of numbers

print(scalar, scalar.ndim, scalar.shape)
print(vector, vector.ndim, vector.shape)
print(matrix, matrix.ndim, matrix.shape)
print(tensor3d.ndim, tensor3d.shape)

tensor(7) 0 torch.Size([])
tensor([1, 2, 3]) 1 torch.Size([3])
tensor([[1, 2],
        [3, 4]]) 2 torch.Size([2, 2])
3 torch.Size([2, 2, 2])


## 14. Creating tensors

In [4]:
# PyTorch provides convenient functions to create tensors with specific patterns
# These are useful for initializing tensors in neural networks

zeros = torch.zeros((2, 3))  # Create a 2×3 tensor filled with zeros
ones = torch.ones((2, 3))  # Create a 2×3 tensor filled with ones
ar = torch.arange(0, 10, 2)  # Create tensor with evenly spaced values: start, end, step
lin = torch.linspace(0, 1, 5)  # Create tensor with 5 evenly spaced values from 0 to 1
rand = torch.rand((2, 3))  # Create 2×3 tensor with random values from uniform distribution [0, 1)
randi = torch.randint(0, 10, (2, 3))  # Create 2×3 tensor with random integers from 0 to 9

print(zeros)
print(ones)
print(ar)
print(lin)
print(rand)
print(randi)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([0, 2, 4, 6, 8])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
tensor([[0.1654, 0.1851, 0.7770],
        [0.9154, 0.7491, 0.7944]])
tensor([[9, 3, 8],
        [2, 5, 7]])


## 17. Tensor datatypes

In [5]:
# Tensor dtype specifies the data type of values (memory and precision trade-off)
# Common types: int32, int64, float32 (default), float64 (double)
# Higher precision (float64) uses more memory; float32 is typical for deep learning

a = torch.tensor([1, 2, 3])  # Default: int64 (inferred from integer input)
b = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)  # Explicitly set to float32
c = b.to(torch.float64)  # Convert tensor to float64 using .to() method

print(a.dtype, b.dtype, c.dtype)

torch.int64 torch.float32 torch.float64


## 18. Tensor attributes

In [6]:
# Every tensor has key attributes that define its structure and properties
# Understanding these helps debug shape mismatches and device issues

t = torch.rand((3, 4), dtype=torch.float32)
print('shape:', t.shape)  # shape: size of each dimension as a tuple (3, 4)
print('ndim:', t.ndim)  # ndim: number of dimensions (2 for a matrix)
print('dtype:', t.dtype)  # dtype: data type of elements (torch.float32)
print('device:', t.device)  # device: where tensor lives (CPU, GPU, etc.)
print('numel:', t.numel())  # numel: total number of elements (3×4 = 12)

shape: torch.Size([3, 4])
ndim: 2
dtype: torch.float32
device: cpu
numel: 12


## 19. Manipulating tensors

In [7]:
# Element-wise operations: operate on corresponding elements at the same position
# These are the fundamental building blocks of neural network computations

x = torch.tensor([1, 2, 3])
y = torch.tensor([10, 20, 30])

print('add:', x + y)  # [11, 22, 33] - add corresponding elements
print('sub:', y - x)  # [9, 18, 27] - subtract corresponding elements
print('mul elementwise:', x * y)  # [10, 40, 90] - multiply corresponding elements (Hadamard product)
print('div:', y / x)  # [10, 10, 10] - divide corresponding elements

add: tensor([11, 22, 33])
sub: tensor([ 9, 18, 27])
mul elementwise: tensor([10, 40, 90])
div: tensor([10., 10., 10.])


## 20. Matrix multiplication

In [8]:
# Matrix multiplication (matmul) is different from element-wise multiplication
# It's essential for neural networks: output = input @ weight + bias
# Rule: (m×n) @ (n×p) = (m×p) - inner dimensions must match!

m1 = torch.tensor([[1., 2., 3.], [4., 5., 6.]])  # Shape: (2, 3) - 2 rows, 3 columns
m2 = torch.tensor([[7., 8.], [9., 10.], [11., 12.]])  # Shape: (3, 2) - 3 rows, 2 columns
print('m1 shape:', m1.shape)  # (2, 3)
print('m2 shape:', m2.shape)  # (3, 2)
print('matmul:', m1 @ m2)  # Result shape: (2, 2) - inner 3's cancel out

m1 shape: torch.Size([2, 3])
m2 shape: torch.Size([3, 2])
matmul: tensor([[ 58.,  64.],
        [139., 154.]])


## 23. Finding min, max, mean, sum

In [9]:
# Aggregation operations: reduce tensors to single values or indices
# These are used for loss computation, finding predictions, and model evaluation

v = torch.tensor([2.0, 5.0, 1.0, 9.0, 3.0])
print('min:', v.min())  # Minimum value in tensor: 1.0
print('max:', v.max())  # Maximum value in tensor: 9.0
print('mean:', v.mean())  # Average of all elements: (2+5+1+9+3)/5 = 4.0
print('sum:', v.sum())  # Sum of all elements: 2+5+1+9+3 = 20.0
print('argmin:', v.argmin())  # Index of minimum value: 2 (v[2] = 1.0)
print('argmax:', v.argmax())  # Index of maximum value: 3 (v[3] = 9.0)

min: tensor(1.)
max: tensor(9.)
mean: tensor(4.)
sum: tensor(20.)
argmin: tensor(2)
argmax: tensor(3)


## 25. Reshaping, viewing and stacking

In [10]:
# Reshaping changes the shape without changing the underlying data (reinterpretation)
# Stacking combines multiple tensors along a new or existing dimension
# These operations are critical for preparing data for neural networks

base = torch.arange(1, 13)  # Create tensor [1, 2, 3, ..., 12] (flat, 1D)
reshaped = base.reshape(3, 4)  # Reinterpret as 3 rows × 4 columns (same 12 elements)
viewed = base.view(2, 6)  # Alternative: view same 12 elements as 2 rows × 6 columns

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print('base:', base)
print('reshape 3x4:', reshaped)
print('view 2x6:', viewed)
print('stack dim0:', torch.stack([a, b], dim=0))  # Stack along new dimension 0 → (2, 3)
print('stack dim1:', torch.stack([a, b], dim=1))  # Stack along new dimension 1 → (3, 2)

base: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
reshape 3x4: tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
view 2x6: tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
stack dim0: tensor([[1, 2, 3],
        [4, 5, 6]])
stack dim1: tensor([[1, 4],
        [2, 5],
        [3, 6]])


## 26. Squeezing, unsqueezing and permuting

In [11]:
# squeeze: removes dimensions of size 1 (useful for cleaning up tensor shapes)
# unsqueeze: adds a dimension of size 1 at a specific position
# permute: rearranges dimensions (useful for converting between data formats)

q = torch.randn(1, 3, 1, 5)  # Shape (1, 3, 1, 5) has redundant dimensions of size 1
print('original:', q.shape)  # (1, 3, 1, 5)
print('squeezed:', q.squeeze().shape)  # (3, 5) - removed all dimensions of size 1

u = q.squeeze().unsqueeze(0)  # Add dimension back at position 0
print('unsqueezed:', u.shape)  # (1, 3, 5) - new dimension at front

# Common in computer vision: NCHW (PyTorch) vs NHWC (NumPy/TensorFlow) formats
# N=batch size, C=channels, H=height, W=width
img = torch.randn(2, 3, 32, 32)  # 2 images, 3 color channels, 32×32 pixels each (NCHW)
print('NCHW:', img.shape)  # (2, 3, 32, 32)
print('NHWC:', img.permute(0, 2, 3, 1).shape)  # (2, 32, 32, 3) - rearrange to NHWC format

original: torch.Size([1, 3, 1, 5])
squeezed: torch.Size([3, 5])
unsqueezed: torch.Size([1, 3, 5])
NCHW: torch.Size([2, 3, 32, 32])
NHWC: torch.Size([2, 32, 32, 3])


## 27. Selecting data (indexing)

In [12]:
# Indexing: access specific elements, rows, columns, or subsets using different methods
# Essential for slicing data batches and extracting specific features from tensors

idx = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  # 3×3 matrix

print('first row:', idx[0])  # [10, 20, 30] - get entire first row
print('last col:', idx[:, -1])  # [30, 60, 90] - get last column (all rows, last column)
print('center:', idx[1, 1])  # 50 - get element at row 1, column 1
print('slice:', idx[0:2, 1:3])  # Get rows 0-1, columns 1-2 (2×2 submatrix)
print('mask > 45:', idx[idx > 45])  # [50, 60, 70, 80, 90] - Boolean masking: get all elements > 45

first row: tensor([10, 20, 30])
last col: tensor([30, 60, 90])
center: tensor(50)
slice: tensor([[20, 30],
        [50, 60]])
mask > 45: tensor([50, 60, 70, 80, 90])


## 28. PyTorch and NumPy

In [13]:
# PyTorch and NumPy can share memory (torch.from_numpy) for efficient conversions
# This means changes to one affect the other - useful but also needs care!
# torch.tensor creates a copy, torch.from_numpy shares memory

arr = np.array([1.0, 2.0, 3.0], dtype=np.float32)
t_from_np = torch.from_numpy(arr)  # Convert NumPy → PyTorch (SHARES memory)

t = torch.tensor([10.0, 20.0, 30.0])
arr_from_t = t.numpy()  # Convert PyTorch → NumPy (SHARES memory)

# Modify original array and tensor - changes propagate to the shared tensor!
arr[0] = 99.0  # Changes NumPy array
t[1] = -5.0  # Changes PyTorch tensor

print('torch from numpy:', t_from_np)  # Notice arr[0] changed, so this changed too
print('numpy from torch:', arr_from_t)  # Notice t[1] changed, so this changed too

torch from numpy: tensor([99.,  2.,  3.])
numpy from torch: [10. -5. 30.]


## 29. Reproducibility

In [14]:
# Random seeds: setting the same seed produces the same random numbers
# Essential for reproducibility: same code + same seed = same results every time
# This is crucial for debugging neural networks and comparing experiments fairly

torch.manual_seed(42)  # Set global random seed to 42
r1 = torch.rand(3)  # Generate random tensor with seed 42

torch.manual_seed(42)  # Reset seed back to 42
r2 = torch.rand(3)  # Generate same random tensor again

print('r1:', r1)
print('r2:', r2)
print('same:', torch.equal(r1, r2))  # True - same seed produces identical random values

r1: tensor([0.8823, 0.9150, 0.3829])
r2: tensor([0.8823, 0.9150, 0.3829])
same: True


## 30. Accessing a GPU

In [15]:
# GPU acceleration: PyTorch can run on GPU (NVIDIA CUDA or Apple MPS) for ~50-100× speedup
# CPU: good for small models, learning, debugging
# GPU: essential for training large models efficiently
# MPS (Metal Performance Shaders): Apple GPU acceleration on Mac

print('CUDA available:', torch.cuda.is_available())  # Check NVIDIA GPU support
print('MPS available:', torch.backends.mps.is_available() if hasattr(torch.backends, 'mps') else False)  # Check Apple GPU
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))  # Print name of first GPU device

CUDA available: False
MPS available: True


## 31. Setting up device agnostic code

In [16]:
# Device-agnostic code: write code that works on CPU, GPU, or MPS automatically
# This is the right way to write production PyTorch code - no need to change code for different hardware

def get_device():
    """Return the best available device for computation."""
    if torch.cuda.is_available():
        return torch.device('cuda')  # Use NVIDIA GPU if available
    if hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():
        return torch.device('mps')  # Use Apple GPU if available
    return torch.device('cpu')  # Fallback to CPU

device = get_device()
print('Using device:', device)

# .to(device) moves tensor or model to the specified device
x = torch.randn(4, 3).to(device)  # Create tensor on the best device
model = torch.nn.Linear(3, 2).to(device)  # Move neural network model to device
out = model(x)  # Forward pass - computes output

print('x device:', x.device)  # Show which device tensor lives on
print('model device:', model.weight.device)  # Show which device model weights are on
print('out shape:', out.shape)  # Output shape: (batch_size=4, output_features=2)

Using device: mps
x device: mps:0
model device: mps:0
out shape: torch.Size([4, 2])


## Practice
- Change shapes and predict outputs before running
- Trigger one matrix shape mismatch to read the error
- Verify NumPy/PyTorch shared memory behavior
- Re-run reproducibility cell and confirm matching random values